name: Docker Image CI

on:
    push:
        branches: ['develop']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Login to DockerHub
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
              run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

            - name: Build the Docker image
              env:
                  DATABASE_URL: ${{ secrets.DATABASE_URL }}
                  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
                  REST_API_KEY: ${{ secrets.REST_API_KEY }}
                  KKT_SECRET_KEY: ${{ secrets.KKT_SECRET_KEY }}
                  KKT_CLIENT_SECRET: ${{ secrets.KKT_CLIENT_SECRET }}
                  REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
                  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
                  AWS_S3_ACCESS_KEY: ${{ secrets.AWS_S3_ACCESS_KEY }}
                  AWS_S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
                  AWS_REGION: ${{ secrets.AWS_REGION }}
                  TOSS_SECRET_KEY: ${{ secrets.TOSS_SECRET_KEY }}
                  AWS_EC2_URL: ${{ secrets.AWS_EC2_URL }}
                  AWS_EC2_CLIENT: ${{ secrets.AWS_EC2_CLIENT }}
                  RES_REDIRECT: ${{ secrets.RES_REDIRECT }}
                  KAKAO_BACK_URL: ${{ secrets.KAKAO_BACK_URL }}
                  KAKO_CLIENT: ${{ secrets.KAKO_CLIENT }}
                  
              run: |
                  docker build \
                    --build-arg DATABASE_URL=${DATABASE_URL} \
                    --build-arg JWT_SECRET_KEY=${JWT_SECRET_KEY} \
                    --build-arg REST_API_KEY=${REST_API_KEY} \
                    --build-arg KKT_SECRET_KEY=${KKT_SECRET_KEY} \
                    --build-arg KKT_CLIENT_SECRET=${KKT_CLIENT_SECRET} \
                    --build-arg REDIRECT_URI=${REDIRECT_URI} \
                    --build-arg AWS_S3_BUCKET=${AWS_S3_BUCKET} \
                    --build-arg AWS_S3_ACCESS_KEY=${AWS_S3_ACCESS_KEY} \
                    --build-arg AWS_S3_SECRET_ACCESS_KEY=${AWS_S3_SECRET_ACCESS_KEY} \
                    --build-arg AWS_REGION=${AWS_REGION} \
                    --build-arg TOSS_SECRET_KEY:${TOSS_SECRET_KEY} \
                    --build-arg AWS_EC2_URL:${AWS_EC2_URL} \
                    --build-arg AWS_EC2_CLIENT:${AWS_EC2_CLIENT} \
                    --build-arg RES_REDIRECT:${RES_REDIRECT} \
                    --build-arg KAKAO_BACK_URL:${KAKAO_BACK_URL} \
                    --build-arg KAKO_CLIENT:${KAKO_CLIENT} \
                    --build-arg TZ=Asia/Seoul \
                    -t seejnn/grabit -f server/Dockerfile server

            - name: Tagging
              run: docker tag seejnn/grabit minsuje/grabit

            - name: Push to DockerHub
              run: docker push seejnn/grabit
